-- Schema version 1. The executable applies the equivalent statements atomically in store.migrate.
-- Kept as a standalone migration artifact for review and packaging.
CREATE TABLE connection_profiles(id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, host TEXT NOT NULL, port INTEGER NOT NULL, selected_version TEXT NOT NULL, compatibility_verified INTEGER NOT NULL DEFAULT 0, command_timeout_ms INTEGER NOT NULL, activation_timeout_ms INTEGER NOT NULL, renewal_interval_ms INTEGER NOT NULL, max_active_jobs INTEGER NOT NULL, history_retention_days INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE job_type_configs(id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES connection_profiles(id) ON DELETE CASCADE, job_type TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', mode TEXT NOT NULL, active_scenario_id TEXT, max_active_jobs INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(profile_id, job_type));
CREATE TABLE scenarios(id TEXT PRIMARY KEY, job_type_config_id TEXT NOT NULL REFERENCES job_type_configs(id) ON DELETE CASCADE, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', outcome TEXT NOT NULL, variables_json TEXT NOT NULL, delay_ms INTEGER NOT NULL DEFAULT 0, error_code TEXT NOT NULL DEFAULT '', error_message TEXT NOT NULL DEFAULT '', remaining_retries INTEGER NOT NULL DEFAULT 0, retry_backoff_ms INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(job_type_config_id, name));
CREATE TABLE activations(id TEXT PRIMARY KEY, profile_id TEXT NOT NULL, job_type_config_id TEXT NOT NULL, job_key TEXT NOT NULL, job_type TEXT NOT NULL, process_instance_key TEXT NOT NULL DEFAULT '', process_definition_key TEXT NOT NULL DEFAULT '', bpmn_process_id TEXT NOT NULL DEFAULT '', element_id TEXT NOT NULL DEFAULT '', element_instance_key TEXT NOT NULL DEFAULT '', retries INTEGER NOT NULL, custom_headers_json TEXT NOT NULL, input_json TEXT NOT NULL, mode TEXT NOT NULL, scenario_snapshot_json TEXT NOT NULL DEFAULT '', draft_json TEXT NOT NULL DEFAULT '', activation_state TEXT NOT NULL, activation_state_reason TEXT NOT NULL DEFAULT '', send_status TEXT NOT NULL, received_at TEXT NOT NULL, prepared_at TEXT NOT NULL DEFAULT '', confirmed_deadline_at TEXT NOT NULL, finished_at TEXT NOT NULL DEFAULT '', profile_snapshot_json TEXT NOT NULL);
CREATE TABLE response_attempts(id TEXT PRIMARY KEY, activation_id TEXT NOT NULL REFERENCES activations(id) ON DELETE CASCADE, sequence INTEGER NOT NULL, command TEXT NOT NULL, payload_json TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT NOT NULL DEFAULT '', duration_ms INTEGER NOT NULL DEFAULT 0, diagnostic_code TEXT NOT NULL DEFAULT '', diagnostic_text TEXT NOT NULL DEFAULT '', UNIQUE(activation_id, sequence));
CREATE TABLE activation_events(id TEXT PRIMARY KEY, activation_id TEXT NOT NULL REFERENCES activations(id) ON DELETE CASCADE, kind TEXT NOT NULL, success INTEGER NOT NULL, details TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE app_settings(key TEXT PRIMARY KEY, value TEXT NOT NULL);
